# Generated by Django 5.1 on 2024-08-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RollerSkateEvent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Child',
        ),
    ]
