# Generated by Django 5.1 on 2024-08-16 08:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RollerSkateInventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('inventories', models.ManyToManyField(to='RollerSkateInventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('client_email', models.CharField(max_length=255)),
                ('borrow_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retrieved_at', models.DateTimeField()),
                ('inventories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='RollerSkateInventory.rollerskate')),
            ],
        ),
    ]
