# Generated by Django 5.1 on 2024-08-17 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RollerSkateInventory', '0003_client_remove_order_client_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date_start',
            new_name='start_time',
        ),
    ]
