# Generated by Django 5.1 on 2024-08-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RollerSkateInventory', '0004_rename_date_end_event_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollerskate',
            name='modulable',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='youremail@email.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rollerskate',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
