# Generated by Django 5.1 on 2024-08-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RollerSkateInventory', '0005_remove_rollerskate_modulable_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='event',
            name='inventories',
        ),
        migrations.RemoveField(
            model_name='order',
            name='event',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rollerskates',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
